### ISSUE TITLE
[Request] Add guide/thoubleshoting 

### ISSUE THREAD

**Issue by master-of-zen** [novomesk/qt-jpegxl-image-plugin#1]
I figured out how to make it and install plugin.
JPEG XL thumbnails don't show up and image viewers don't recognize it, please help)

**Comment by novomesk** [comment]
In order to activate thumbnails, it is necessary to update `/usr/share/kservices5/imagethumbnail.desktop` and the `image/jxl` mimetype (image-jxl.xml) should be installed.

In order to troubleshot I recommend to start `gwenview` from konsole to see various debug/error messages:
`gwenview testimage.jxl`

Jxl animations are known not to work now because of https://gitlab.com/wg1/jpeg-xl/-/issues/87

I also use the `opt` parameter to configure libjxl to see libjxl's internal error messages.
`BUILD_DIR=/tmp/build ./ci.sh opt`

**Comment by master-of-zen** [comment]
Excuse me for newby mistakes)
This issue, not sure how to how to interpret it

Out of all steps only 
`image/jxl mimetype (image-jxl.xml) should be installed.` is not done, don't know how to do that.
Added file association in settings manually 
Console 
```
> gwenview output.jxl 
Icon theme "gnome" not found.
org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-mng"
org.kde.kdegraphics.gwenview.lib: Unresolved raw mime type  "image/x-nikon-nrw"
org.kde.kdegraphics.gwenview.lib: Unresolved raw mime type  "image/x-samsung-srw"
```

Gwenview gui show this error 
![2020_12_29_12_36_32](https://user-images.githubusercontent.com/46526140/103277849-9499cf80-49d2-11eb-8d1a-8ad1b17cb001.png)


My imagethumbnail.desktop
[thumbnails.zip](https://github.com/novomesk/qt-jpegxl-image-plugin/files/5750335/thumbnails.zip)

and here file itself
[file.zip](https://github.com/novomesk/qt-jpegxl-image-plugin/files/5750327/file.zip)

**Comment by novomesk** [comment]
Copy `image-jxl.xml` into the folder
`/usr/share/mime/packages`

I use slightly modified version ( https://gitlab.com/wg1/jpeg-xl/-/issues/81 ):
```
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="image/jxl">
    <comment>JPEG XL image</comment>
    <comment xml:lang="fr">image JPEG XL</comment>
    <magic priority="50">
      <match type="string" offset="0" value="\xFF\x0A"/>
      <match type="string" offset="0" value="\0\0\0\x0CJXL \x0D\x0A\x87\x0A"/>
    </magic>
    <glob pattern="*.jxl"/>
  </mime-type>
</mime-info>
```

I think you made a mistake because you registered image/jpegxl and I believe it should be image/jxl

Run `update-mime-database /usr/share/mime`

and try again:
![output](https://user-images.githubusercontent.com/52529860/103279478-2a7f2b80-49ce-11eb-90ea-c0434d3f9196.png)

**Comment by master-of-zen** [comment]
done:
`Copy image-jxl.xml into the folder
/usr/share/mime/packages`
changed:
`I think you made a mistake because you registered image/jpegxl and I believe it should be image/jxl`
done:
`Run update-mime-database /usr/share/mime`

Still doesn't work.
same console errors
![2020_12_29_13_23_51](https://user-images.githubusercontent.com/46526140/103280479-30c6d500-49d9-11eb-8108-fe09f6644c91.png)

**Comment by novomesk** [comment]
I get same message when my plugin is missing or could not be loaded.
I have libqjpegxl.so in `/usr/lib64/qt5/plugins/imageformats` folder. On some systems it could be `/usr/lib/qt/plugins/imageformats/` or `/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats`

If it is there, try to go to the folder and check `ldd libqjpegxl.so` if all required libraries are present.

**Comment by master-of-zen** [comment]
`libjxl.so.0 => not found
 libjxl_threads.so.0 => not found` 
for `/usr/lib/qt/plugins/imageformats/libqjpegxl.so`

libjpegxl installed
```
-- Up-to-date: /usr/local/lib/libjxl.a
-- Up-to-date: /usr/local/lib/libjxl.so.0.2.0
-- Up-to-date: /usr/local/lib/libjxl.so.0
-- Up-to-date: /usr/local/lib/libjxl.so
-- Up-to-date: /usr/local/lib/pkgconfig/libjxl.pc
-- Up-to-date: /usr/local/lib/libjxl_threads.a
-- Up-to-date: /usr/local/lib/libjxl_threads.so.0.2.0
-- Up-to-date: /usr/local/lib/libjxl_threads.so.0
-- Up-to-date: /usr/local/lib/libjxl_threads.so
```

**Comment by novomesk** [comment]
OK, you found the problem!
I have them installed in `/usr/lib64`
Try to copy or symlink it there (or maybe `/usr/lib` on some systems) so the libjxl and libjxl_threads will be found easily.

**Comment by master-of-zen** [comment]
Yep, it works now))
