### ISSUE TITLE
[Probably bug] Issue with encoding/decoding files with resolution that are not multiple of 8

### ISSUE THREAD

**Issue by master-of-zen** [novomesk/qt-jpegxl-image-plugin#2]
[files.zip](https://github.com/novomesk/qt-jpegxl-image-plugin/files/5752723/files.zip)
Issue with encoding/decoding files with resolution that are not multiple of 8.
Check this thread on twitter with Jon Sneyers
https://twitter.com/jonsneyers/status/1343936322214498307
Original image and encoded jxl

**Comment by novomesk** [comment]
Thanks for testing and reporting.
Well, this problem manifested when I requested 8bit format with 3 channels (without alpha channel). When I requested 4 channels, situation got improved. I don’t know where the origin of the problem is.

Anyway, now the plug-in works in 16bit depth. Please test again and if it works for you, you may close this issue.

**Comment by master-of-zen** [comment]
![2020_12_31_03_27_58](https://user-images.githubusercontent.com/46526140/103389552-40990300-4b18-11eb-9094-789ec0617f1f.png)
Opening image is fine, but thumbnails still bad

**Comment by novomesk** [comment]
Does it happen after restart on newly created files too?

**Comment by master-of-zen** [comment]
@novomesk After restart everything is fine :)
